services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: mpaeureview.settings
      PORT: "8000"
      WEB_CONCURRENCY: "3"
    volumes:
      - ./data/media:/app/media
