# Generated by Django 5.1.7 on 2025-11-10 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('text', models.CharField(max_length=255)),
                ('explanation', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('question_type', models.CharField(choices=[('radio', 'Radio (Multiple Choice)'), ('text', 'Free Text')], default='radio', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site status',
                'verbose_name_plural': 'Site status',
            },
        ),
        migrations.CreateModel(
            name='SpeciesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignedSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=100)),
                ('species_key', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Assigned species',
                'verbose_name_plural': 'Assigned species',
                'unique_together': {('user_code', 'species_key')},
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=100)),
                ('species_key', models.CharField(max_length=100)),
                ('question_key', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('user_code', 'species_key', 'question_key')},
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='review.question')),
            ],
        ),
        migrations.CreateModel(
            name='SkippedSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=100)),
                ('species_key', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('user_code', 'species_key')},
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.speciesgroup')),
            ],
            options={
                'verbose_name': 'Species',
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=100, unique=True)),
                ('must_change_password', models.BooleanField(default=True)),
                ('consent_accepted', models.BooleanField(default=False)),
                ('consent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('consent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('groups', models.ManyToManyField(to='review.speciesgroup')),
            ],
            options={
                'verbose_name': 'User access',
                'verbose_name_plural': 'Users access',
            },
        ),
    ]
