# Generated by Django 5.1.7 on 2025-11-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('radio', 'Radio (Multiple Choice)'), ('text', 'Free Text'), ('map', 'Map drawing')], default='radio', max_length=10),
        ),
    ]
