# Generated by Django 5.1.7 on 2025-05-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_questionoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkippedSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=100)),
                ('species_key', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('user_code', 'species_key')},
            },
        ),
    ]
