# Generated by Django 5.1.7 on 2025-05-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_skippedspecies'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
