# Generated by Django 5.1.7 on 2025-05-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_species_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='consent_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
