# Generated by Django 5.1.7 on 2025-05-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_species_consent_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
