# Generated by Django 5.1.7 on 2025-05-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_species_consent_ip_species_consent_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='consent_accepted',
        ),
        migrations.RemoveField(
            model_name='species',
            name='consent_ip',
        ),
        migrations.RemoveField(
            model_name='species',
            name='consent_timestamp',
        ),
        migrations.RemoveField(
            model_name='species',
            name='must_change_password',
        ),
        migrations.AddField(
            model_name='useraccess',
            name='consent_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
