# Generated by Django 5.1.7 on 2025-05-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_remove_species_consent_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('radio', 'Radio (Multiple Choice)'), ('text', 'Free Text')], default='radio', max_length=10),
        ),
    ]
