# Generated by Django 5.1.7 on 2025-05-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_question_explanation_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
