# Generated by Django 5.1.7 on 2025-05-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_alter_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='value',
            field=models.CharField(max_length=300),
        ),
    ]
