# Generated by Django 5.1.7 on 2025-05-22 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_question_is_required_alter_question_explanation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='useraccess',
            name='group',
        ),
        migrations.AddField(
            model_name='useraccess',
            name='groups',
            field=models.ManyToManyField(to='review.speciesgroup'),
        ),
        migrations.AlterField(
            model_name='species',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.speciesgroup'),
        ),
    ]
